### ISSUE TITLE
Webclips going to default texture after reboot/ipad dies

### ISSUE THREAD

**Issue by dontbanmeplz** [sourcelocation/TrollTools#13]
All webclips break entirely after restart, apps dont open and just crash, textures are gone.

**Comment by sourcelocation** [comment]
Webclips reset because of TrollStore's limitations. Make sure to refresh app registrations if apps stop working

**Comment by dontbanmeplz** [comment]
> Webclips reset because of TrollStore's limitations. Make sure to refresh app registrations if apps stop working

wait what does this mean
@sourcelocation

**Comment by sourcelocation** [comment]
You can refresh app registrations inside TrollStore Helper (usually people install it into Tips app)

**Comment by dontbanmeplz** [comment]
Perfect thanks
