### ISSUE TITLE
v2.1 bug: Icons with & without -large are considered as " items with the same name "

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/TrollTools#14]
When adding a theme on v2.1 if it contains two icons of the same app that one of them has " -large " it will consider these two icons as " items with the same name " :

![image](https://user-images.githubusercontent.com/67245917/200145915-4fb9deee-bda0-42f2-9801-e053977e51c7.jpeg)

![image](https://user-images.githubusercontent.com/67245917/200145934-3c617428-3bd6-41f9-ada0-88d8aa01b43b.jpeg)

and the theme doesn't get added to the list (although it is added in the TrollToolsThemes folder). 

![image](https://user-images.githubusercontent.com/67245917/200146098-eac19bd2-ff6f-4b71-8724-9acad9bcf2bb.jpeg)

This wasn't an issue before. 

I had to delete all the "_duplicated_" icons without " -large " to import the theme. 

**iPhone 12 Pro Max
iOS 15.1.1
TrollTools  2.1**

**Comment by sourcelocation** [comment]
Hi AymenKcm1, thanks for creating this detailed issue. I will fix this issue tomorrow

**Comment by sourcelocation** [comment]
Fixed in 2.1.1
