### ISSUE TITLE
LockScreen Keyboard shrinking

### ISSUE THREAD

**Issue by huligang** [sourcelocation/TrollTools#2]
LockScreen Keyboard Shrinking
![IMG_3381](https://user-images.githubusercontent.com/26988903/197914063-69a14489-0aaf-46db-a653-c5f3155909e5.PNG)

**Comment by huligang** [comment]
iPhone 12 Pro iOS15.2 TrollTools v2.0

**Comment by sourcelocation** [comment]
Hi, are there any margins on the sides of source images? If there aren't, could you please send me the key set so I can reproduce the issue?

**Comment by huligang** [comment]
Please give me an email address.

**Comment by sourcelocation** [comment]
you can use this issues comments or join my discord server for faster communication https://discord.gg/VyVcNjRMeg

**Comment by sourcelocation** [comment]
Fixed in 2.1
