### ISSUE TITLE
[Bug] Doesn't theme Filza

### ISSUE THREAD

**Issue by korboybeats** [sourcelocation/TrollTools#3]
I have a `com.tigisoftware.Filza-large.png` file but it doesn't theme Filza.

**Comment by sourcelocation** [comment]
Hi, it's a known bug, currently fixing it

**Comment by erdongchanyo** [comment]
Hello, I made some icons myself, most of them can be modified by TrollTools, but there are a few APPs that can't be modified successfully

as follows.

wechat: com.tencent.xin-large.png
Loon: com.ruikq.decar-large.png

**Comment by erdongchanyo** [comment]
Hello, I made some icons myself, most of them can be modified by TrollTools, but there are a few APPs that can't be modified successfully
as follows.
wechat: com.tencent.xin-large.png
Loon: com.ruikq.decar-large.png

**Comment by sourcelocation** [comment]
This will be fixed in 2.0.1 which will come out very soon (one hour or so)

**Comment by erdongchanyo** [comment]
Looking forward to it

**Comment by sourcelocation** [comment]
Fixed in 2.0.1, https://github.com/sourcelocation/TrollTools/commit/7863a67b67df2fe4fdabb6c12549278dadb3456e
