### ISSUE TITLE
[bug] keypad icons will not change to small state

### ISSUE THREAD

**Issue by ghost** [sourcelocation/TrollTools#30]
Description:

Custom keypad icons will not switch to the small or big state. The button is often frozen and will only affect some icons

To reproduce:
1. Add custom icons to all the keypads. Mine were 256x256.
2. Check to see if it worked. They should all be big.
3. Relaunch the app and click ‘small’, changing it to big
4. Check to see if it worked. 

Expected behavior:

All the icons are small

actual behavior:

for me, the ‘0’ key was small, and all the others were still big.

Platform:

iOS 15.0.2 on iPad Mini 5. TrollTools 2.1.2, Trollstore 1.3.5

**Comment by Cestb0n** [comment]
I'm the same situation. Every time it happens, the number 0 needs to be set separately.

**Comment by leminlimez** [comment]
This will be fixed in the next release

**Comment by a887234z** [comment]
Gooooood
