### ISSUE TITLE
Applying a second theme keeps the old theme " In use "

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/TrollTools#4]
I don't know if this could cause any issues or not, but when I have an already active theme and activate a second theme the old theme is marked as " In use " when it should be deactivated. 

![image](https://user-images.githubusercontent.com/67245917/198702220-4f40c46f-37af-4e87-b055-7dc9b6a8c755.jpeg)

If this is just a UI bug good, if not it should definitely deactivate old theme before applying the new one. 

iPhone **12 Pro Max** 
iOS **15.1.1**
TrollTools **v2.0.1**
TrollStore **v1.2.2**

**Comment by sourcelocation** [comment]
Hi, it's not a bug, it's an intended feature to allow combining similar themes, because often themes don't have all app icons installed on your phone. Thanks for talking your time to make an issue though!

**Comment by sourcelocation** [comment]
If you want to disable previious theme, you can press the trash button in the top left corner

**Comment by AymenKcm1** [comment]
Thanks, that worked great 🙂

But by that logic shouldn't the icon be a RESET icon (similar to 🔄 or ↩️) instead of a trash icon which by default means DELETING themes, which is what I thought first, but then after you explained this to me I tapped and held on a theme to reveal the " Remove theme " button. 

Keep this in mind for the next update. 

Thanks again 👍

**Comment by sourcelocation** [comment]
Good point
