### ISSUE TITLE
Not able to load themes 

### ISSUE THREAD

**Issue by Johnnyfilauptown** [sourcelocation/TrollTools#40]
I keep getting message that says i dont have permission to save the file when i try to add themes. Please help

**Comment by sourcelocation** [comment]
what ios version?

**Comment by sourcelocation** [comment]
sorry for super late reply

**Comment by johnnyfila** [comment]
Ios 16.2

**Comment by sourcelocation** [comment]
you can't use TrollTools on >15.4.1. Only works on TrollStore versions

**Comment by sourcelocation** [comment]
(you can use palera1n of course, but I suppose you don't have it installed)

**Comment by johnnyfila** [comment]
No i dont. Will it work for iphone 12 pro ios 16.2 ?
