### ISSUE TITLE
(Possibly) Inaccurate App counter

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/TrollTools#5]
Hi, I have 370 apps (😅) installed

![image](https://user-images.githubusercontent.com/67245917/198719020-972f3610-7be5-40e7-af80-f88d26f2cdf3.jpeg)

and when applying a theme it shows a total app number of 556 and not 370 (or number of total icons it's going to apply) 

![image](https://user-images.githubusercontent.com/67245917/198719202-0f94c23b-3ce5-4fbf-a3ed-10ef9ce87b77.jpeg)

Even with system apps that it will create Webclips for it doesn't reach 556 apps.

What does that number represent? 

Does include system-wide icons? (Like app icons in Settings / Notifications...)

If it's for just installed apps number it's not accurate, if it includes additional things please mention them to clarify this.

Thanks.

**Comment by sourcelocation** [comment]
Hi, can confirm this is in fact a bug. I don’t know exactly what rest of apps represent, because apple doesn’t like to document private apis haha. I’ll fix this bug in 2.1, as its not critical. Thanks for creating an issue

**Comment by AymenKcm1** [comment]
Happy to help 😊

**Comment by sourcelocation** [comment]
Fixed in 2.1. No longer shows app count, but rather percentage
