### ISSUE TITLE
Themed icons back to original after app update

### ISSUE THREAD

**Issue by AymenKcm1** [sourcelocation/TrollTools#7]
Hi,

I know this is a long shot and maybe not possible, but is there a way to make the app icon persist after an app is updated from Appstore? 

Or maybe add an option to quickly refresh / reapply a theme without having to deactivate & reactivate it and wait for all icons to be applied all over again.

I hope it's possible 🤞

**Comment by sourcelocation** [comment]
Hi, sadly, it isn't possible to create an automatic solution, but a quick refresh would be nice. I'll keep that in mind for 2.1

**Comment by sourcelocation** [comment]
Partially fixed in 2.1 with new selection method. Feel free to reopen this issue if needed
